export const ACTION_USER_TYPES = {
  SET_CURRENT_USER: "userData/SET_CURRENT_USER",
  SET_USER_LOGIN: "SET_USER_LOGIN",
  SET_CLICK_PLAYLIST: "SET_CLICK_PLAYLIST",
  SET_CURRENT_CLICK_PLAYLIST: "SET_CURRENT_CLICK_PLAYLIST",
  SET_AUDIO: "SET_AUDIO",
  SET_RANDOM_PLAYLIST: "SET_RANDOM_PLAYLIST",
};
